# Generated by Django 3.2.3 on 2021-05-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_mvt', '0002_alter_student_year_of_graudation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year_of_graudation',
            new_name='year_of_graduation',
        ),
    ]
