# Generated by Django 3.2.3 on 2021-05-20 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_mvt', '0003_rename_year_of_graudation_student_year_of_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_django_mvt.department'),
        ),
    ]
